"""ComplexGitSync package."""

from .client import ComplexGitSyncClient
from .errors import (
    ArchitectureNotLoadedError,
    ComplexGitSyncError,
    ConfigValidationError,
    FallbackRejectedError,
    GitSyncError,
    NestedConfigDiscoveryError,
    TreeNotReadyError,
)
from .models import (
    DependencyTreeRegistry,
    DiscoveryState,
    FallbackDecision,
    GitTreeStateSnapshot,
    InteractionMode,
    LeafRepo,
    LoadedSession,
    NodeType,
    OperationResult,
    OutputProfile,
    ParentRepo,
    ProjectArchitecture,
    ProjectTreeState,
    RefKind,
    RepoNode,
    RepoLifecycleState,
    RepoOutcome,
    RepoRefPolicy,
    RepoRegistryEntry,
    RepoSpec,
    RequestedRef,
    ResolvedRef,
    RuntimeOptions,
    SyncState,
    TreeLifecycleState,
)

__all__ = [
    "ArchitectureNotLoadedError",
    "ComplexGitSyncClient",
    "ComplexGitSyncError",
    "ConfigValidationError",
    "DependencyTreeRegistry",
    "DiscoveryState",
    "FallbackDecision",
    "FallbackRejectedError",
    "GitTreeStateSnapshot",
    "GitSyncError",
    "InteractionMode",
    "LeafRepo",
    "LoadedSession",
    "NestedConfigDiscoveryError",
    "NodeType",
    "OperationResult",
    "OutputProfile",
    "ParentRepo",
    "ProjectArchitecture",
    "ProjectTreeState",
    "RefKind",
    "RepoNode",
    "RepoLifecycleState",
    "RepoOutcome",
    "RepoRefPolicy",
    "RepoRegistryEntry",
    "RepoSpec",
    "RequestedRef",
    "ResolvedRef",
    "RuntimeOptions",
    "SyncState",
    "TreeLifecycleState",
    "TreeNotReadyError",
]

__version__ = "0.1.0"
