"""Backward-compatible re-export shim — registry types now live in git_tree.py;
builder functions now live in orchestre.py."""
from .git_repo import (
    AccessProtocol,
    DiscoveryState,
    GitProvider,
    NodeType,
    RefKind,
    RepoLifecycleState,
    RepoNode,
    RepoRegistryEntry,
    SyncState,
)
from .git_tree import (
    ROOT_REPO_ID,
    DependencyTreeRegistry,
    ProjectTreeState,
    TreeLifecycleState,
    _apply_repo_identity,
    _initial_discovery_state,
    _normalise_relative_path,
    _parse_enum,
    _validate_repo_shape,
    build_tree_state,
    make_repo_id,
    promote_to_parent,
    register_relative_path,
)
from .orchestre import (
    build_gts_document_from_registry,
    build_registry_from_cgs_document,
    build_registry_from_gts_document,
)

__all__ = [
    "ROOT_REPO_ID",
    "AccessProtocol",
    "DependencyTreeRegistry",
    "DiscoveryState",
    "GitProvider",
    "NodeType",
    "ProjectTreeState",
    "RefKind",
    "RepoLifecycleState",
    "RepoNode",
    "RepoRegistryEntry",
    "SyncState",
    "TreeLifecycleState",
    "build_gts_document_from_registry",
    "build_registry_from_cgs_document",
    "build_registry_from_gts_document",
    "build_tree_state",
    "make_repo_id",
    "promote_to_parent",
    "register_relative_path",
    "_apply_repo_identity",
    "_initial_discovery_state",
    "_normalise_relative_path",
    "_parse_enum",
    "_validate_repo_shape",
]
