# CaWaQS-Viz Git Tree State snapshot
# ──────────────────────────────────────────────────────────────────────────────
# This .gts file is GENERATED by ComplexGitSync after a successful initialise,
# pull, or checkout.  Do not edit by hand.  Use it with pull to replay the exact
# recorded state without requiring .cgs discovery.

[document]
format_version = "1.0"
generated_at   = "2026-05-12T22:30:00Z"
command_origin = "clone"

[project]
name               = "CaWaQS-Viz"
root_absolute_path = "/workspace/CaWaQS-Viz"
source_cgs_path    = "/workspace/CaWaQS-Viz/cawaqsviz.cgs"

[tree_state]
lifecycle_state   = "READY"
is_ready          = true
registry_complete = true

# ── Per-repo state ──────────────────────────────────────────────────────────

[[repo_state]]
name                 = "CaWaQS-Viz"
node_type            = "ParentRepo"
absolute_path        = "/workspace/CaWaQS-Viz"
relative_path        = "."
source_cgs_path      = "/workspace/CaWaQS-Viz/cawaqsviz.cgs"
repo_lifecycle_state = "READY"
sync_state           = "ALIGNED"
current_ref_kind     = "branch"
current_ref_name     = "main"
resolved_ref_kind    = "branch"
resolved_ref_name    = "main"
target_ref_kind      = "branch"
target_ref_name      = "main"
commit_sha           = "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2"
fallback_applied     = false
discovery_state      = "RESOLVED"
worktree_state       = "CLEAN"
is_reachable         = true

[[repo_state]]
name                 = "HydrologicalTwinAlphaSeries"
node_type            = "ParentRepo"
absolute_path        = "/workspace/CaWaQS-Viz/external/HydrologicalTwinAlphaSeries"
relative_path        = "external/HydrologicalTwinAlphaSeries"
parent_absolute_path = "/workspace/CaWaQS-Viz"
source_cgs_path      = "/workspace/CaWaQS-Viz/external/HydrologicalTwinAlphaSeries/htas.cgs"
repo_lifecycle_state = "READY"
sync_state           = "ALIGNED"
current_ref_kind     = "branch"
current_ref_name     = "main"
resolved_ref_kind    = "branch"
resolved_ref_name    = "main"
target_ref_kind      = "branch"
target_ref_name      = "main"
commit_sha           = "b2c3d4e5f6a7b2c3d4e5f6a7b2c3d4e5f6a7b2c3"
fallback_applied     = false
discovery_state      = "RESOLVED"
worktree_state       = "CLEAN"
is_reachable         = true

[[repo_state]]
name                 = "hydrological_twin"
node_type            = "LeafRepo"
absolute_path        = "/workspace/CaWaQS-Viz/external/HydrologicalTwinAlphaSeries/docs/hydrological_twin"
relative_path        = "docs/hydrological_twin"
parent_absolute_path = "/workspace/CaWaQS-Viz/external/HydrologicalTwinAlphaSeries"
source_cgs_path      = "/workspace/CaWaQS-Viz/external/HydrologicalTwinAlphaSeries/htas.cgs"
repo_lifecycle_state = "READY"
sync_state           = "ALIGNED"
current_ref_kind     = "branch"
current_ref_name     = "main"
resolved_ref_kind    = "branch"
resolved_ref_name    = "main"
target_ref_kind      = "branch"
target_ref_name      = "main"
commit_sha           = "c3d4e5f6a7b8c3d4e5f6a7b8c3d4e5f6a7b8c3d4"
fallback_applied     = false
discovery_state      = "RESOLVED"
worktree_state       = "CLEAN"
is_reachable         = true

[[repo_state]]
name                 = "CWV_user_guide"
node_type            = "LeafRepo"
absolute_path        = "/workspace/CaWaQS-Viz/docs/CWV_user_guide"
relative_path        = "docs/CWV_user_guide"
parent_absolute_path = "/workspace/CaWaQS-Viz"
source_cgs_path      = "/workspace/CaWaQS-Viz/cawaqsviz.cgs"
repo_lifecycle_state = "READY"
sync_state           = "ALIGNED"
current_ref_kind     = "branch"
current_ref_name     = "main"
resolved_ref_kind    = "branch"
resolved_ref_name    = "main"
target_ref_kind      = "branch"
target_ref_name      = "main"
commit_sha           = "d4e5f6a7b8c9d4e5f6a7b8c9d4e5f6a7b8c9d4e5"
fallback_applied     = false
discovery_state      = "RESOLVED"
worktree_state       = "CLEAN"
is_reachable         = true
