"""Tests for gts_integrity — the three-level State hash.

The golden vectors below are the cross-platform contract of
``integrity_schema = 1``: fixed leaf dicts must give these exact digests on
Linux, macOS and Windows. They were generated by an independent, from-scratch
RFC 6962 implementation, not by the module under test. A change that moves
any of them is a new integrity schema, never an edit to this file.
"""

from __future__ import annotations

import pytest

from ComplexGitSync.errors import ConfigValidationError
from ComplexGitSync.gts_integrity import INTEGRITY_SCHEMA, GtsIntegrity


def _leaf(index: int) -> dict:
    return {
        "name": f"repo{index}",
        "relative_path": "." if index == 0 else f"lib/r{index}",
        "commit_sha": f"{index:040x}",
        "current_ref": "branch:main",
        "repo_lifecycle_state": "READY",
        "is_reachable": True,
        "fallback_reason": None,
    }


GOLDEN_ROOTS = {
    1: "4077f8c681896dd6a214038eecb18815355fa94c1096e7e41d5324a49d59aa4a",
    2: "f25b6b0c1bccd556ed276e638cb5df0242369999802f761772cf474e5e61b9f1",
    3: "d465693a8d36cf7a28ed48e253aefa4036cf447ba70492f06d600c595e6b17d4",
    4: "b98e0cce296d6f8d117079161397f7c490d06abb78b4a4b02858710071f08a2c",
    5: "160a9f9f1fede963985f10f43ebc450faf2e8c67440195eacf8817a0465e66f3",
    7: "860f0ad35ec2618b85d11c9bbe9a17384d2ff40e2a50759e44d8c855f3dc7f3e",
}
GOLDEN_LEAF_0 = "4077f8c681896dd6a214038eecb18815355fa94c1096e7e41d5324a49d59aa4a"
GOLDEN_STATE_1 = "431ad6b9108e7ddac03e40043c72a9381b6d1a6e8a133d6c79a25d974d3a99c3"


def test_the_schema_is_one():
    assert INTEGRITY_SCHEMA == 1


def test_golden_leaf():
    assert GtsIntegrity.repo_leaf_hash(_leaf(0)) == GOLDEN_LEAF_0


@pytest.mark.parametrize("count", sorted(GOLDEN_ROOTS))
def test_golden_merkle_roots(count):
    leaves = [_leaf(index) for index in range(count)]
    assert GtsIntegrity.merkle_root(leaves) == GOLDEN_ROOTS[count]


def test_golden_state():
    payload = {
        "project": {"name": "demo"},
        "tree_state": {"lifecycle_state": "READY", "is_ready": True, "registry_complete": True},
        "gittree_root": GtsIntegrity.merkle_root([_leaf(0)]),
        "freeze_manifest": None,
    }
    assert GtsIntegrity.state_hash(payload) == GOLDEN_STATE_1


def test_one_leaf_is_its_own_root():
    assert GtsIntegrity.merkle_root([_leaf(0)]) == GtsIntegrity.repo_leaf_hash(_leaf(0))


def test_three_leaves_split_two_then_one_with_no_duplicated_leaf():
    """RFC 6962 §2.1: k = 2 for N = 3, and the last leaf is promoted as is."""
    digests = [bytes.fromhex(GtsIntegrity.repo_leaf_hash(_leaf(index))) for index in range(3)]
    expected = GtsIntegrity.node_hash(GtsIntegrity.node_hash(digests[0], digests[1]), digests[2])
    assert GtsIntegrity.merkle_root([_leaf(index) for index in range(3)]) == expected.hex()


def test_the_domain_tags_separate_a_leaf_from_a_state():
    leaf = _leaf(0)
    assert GtsIntegrity.repo_leaf_hash(leaf) != GtsIntegrity.state_hash(leaf)


def test_an_empty_tree_has_the_rfc_6962_empty_root():
    """MTH({}) = SHA-256 of the empty string; only a never-READY State has it."""
    assert GtsIntegrity.merkle_root([]) == "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"


def test_a_duplicate_relative_path_is_refused_not_tie_broken():
    twin = dict(_leaf(1), name="other")
    with pytest.raises(ConfigValidationError, match="duplicate relative_path"):
        GtsIntegrity.merkle_root([_leaf(0), _leaf(1), twin])


def test_a_leaf_without_a_relative_path_is_refused():
    leaf = _leaf(1)
    del leaf["relative_path"]
    with pytest.raises(ConfigValidationError, match="no relative_path"):
        GtsIntegrity.merkle_root([_leaf(0), leaf])
