name: CI

on:
  push:
    branches: [main, lechat]
  pull_request:
    branches: [main, lechat]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
      - name: Install package
        run: pixi install
      - name: Lint
        run: pixi run lint
      - name: Run tests
        run: pixi run test
